services:
    App\Commands\Handlers\:
        resource: '../../Commands/Handlers/'
        autowire: true
        tags:
            - { name: tactician.handler }

    App\Queries\Handlers\:
        resource: '../../Queries/Handlers/'
        autowire: true
        tags:
            - { name: tactician.handler }
